window.TRAILS = [
  {
    "id": "algar-do-carv-o-furnas-do-enxofre",
    "title": "Algar do Carvão – Furnas do Enxofre",
    "code": "PRC10TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/algar-do-carvao-furnas-do-enxofre-768x346.jpg",
    "location": "Angra do Heroísmo, Porto Judeu",
    "distance": "6,2 Km",
    "type": "Circular",
    "difficulty": "Médio",
    "duration": "2h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/algar-do-carvao-furnas-do-enxofre/"
  },
  {
    "id": "ba-as-da-agualva",
    "title": "Baías da Agualva",
    "code": "PR02TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/baias-da-agualva-768x511.jpg",
    "location": "Praia da Vitória, Agualva",
    "distance": "3,9 Km",
    "type": "Linear",
    "difficulty": "Fácil",
    "duration": "2h00",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/baias-da-agualva/"
  },
  {
    "id": "fortes-de-s-o-sebasti-o",
    "title": "Fortes de São Sebastião",
    "code": "PR05TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2026/02/fortes-de-sao-sebastiao-768x461.webp",
    "location": "Angra do Heroísmo, São Sebastião",
    "distance": "5,9 Km",
    "type": "Linear",
    "difficulty": "Fácil",
    "duration": "2h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/fortes-de-sao-sebastiao/"
  },
  {
    "id": "grande-rota-do-oeste",
    "title": "Grande Rota do Oeste",
    "code": "GR01TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/grande-rota-do-oeste-1.webp",
    "location": "Angra do Heroísmo, São Bartolomeu de Regatos",
    "distance": "31,2 Km",
    "type": "Linear",
    "difficulty": "Difícil",
    "duration": "10h00",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/grande-rota-do-oeste/"
  },
  {
    "id": "grande-rota-do-oeste-etapa-1-lagoa-das-patas-pico-negr-o",
    "title": "Grande Rota do Oeste – Etapa 1: Lagoa das Patas – Pico Negrão",
    "code": "GR01TERE01",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/GRota-Oeste-etapa-1-768x452.webp",
    "location": "Angra do Heroísmo",
    "distance": "21,9 Km",
    "type": "Linear",
    "difficulty": "Difícil",
    "duration": "07h00",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/grande-rota-do-oeste-lagoa-das-patas-pico-negrao/"
  },
  {
    "id": "grande-rota-do-oeste-etapa-2-pico-negr-o-mata-da-serreta",
    "title": "Grande Rota do Oeste – Etapa 2: Pico Negrão – Mata da Serreta",
    "code": "GR01TERE02",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2025/04/grande-rota-do-oeste-pico-negrao-mata-da-serreta-768x432.webp",
    "location": "Angra do Heroísmo, Serreta",
    "distance": "9,3 Km",
    "type": "Linear",
    "difficulty": "Difícil",
    "duration": "03h00",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/grande-rota-do-oeste-pico-negrao-mata-da-serreta/"
  },
  {
    "id": "lagoa-do-cerro",
    "title": "Lagoa do Cerro",
    "code": "PRC13TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2025/07/PRC13TER-Lagoa-do-Cerro-Foto-768x512.jpg",
    "location": "Angra do Heroísmo",
    "distance": "6,4 Km",
    "type": "Circular",
    "difficulty": "Fácil",
    "duration": "02h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/lagoa-do-cerro/"
  },
  {
    "id": "malha-grande-biscoitos",
    "title": "Malha Grande – Biscoitos",
    "code": "PR09TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/malha-grande-biscoitos-768x432.jpg",
    "location": "Praia da Vitória, Biscoitos",
    "distance": "14,4 Km",
    "type": "Linear",
    "difficulty": "Médio",
    "duration": "3h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/malha-grande-biscoitos/"
  },
  {
    "id": "matas-da-agualva",
    "title": "Matas da Agualva",
    "code": "PRC14TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2026/04/IMG_20260311_140919-768x575.webp",
    "location": "Praia da Vitória, Agualva",
    "distance": "7,7 Km",
    "type": "Circular",
    "difficulty": "Médio",
    "duration": "02h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/matas-da-agualva/"
  },
  {
    "id": "mist-rios-negros",
    "title": "Mistérios Negros",
    "code": "PRC01TER",
    "image": "https://turismo.azores.gov.pt/wp-content/uploads/2024/10/misterios-negros-768x346.jpg",
    "location": "Angra do Heroísmo",
    "distance": "5,2 Km",
    "type": "Circular",
    "difficulty": "Difícil",
    "duration": "2h30",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/misterios-negros/"
  },
  {
    "id": "monte-brasil",
    "title": "Monte Brasil",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/monte-brasil/"
  },
  {
    "id": "passagem-das-bestas",
    "title": "Passagem das Bestas",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/passagem-das-bestas/"
  },
  {
    "id": "pedra-furada-da-serra-da-ribeirinha",
    "title": "Pedra Furada da Serra da Ribeirinha",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/pedra-furada-da-serra-da-ribeirinha/"
  },
  {
    "id": "relheiras-de-sao-bras",
    "title": "Relheiras de São Brás",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/relheiras-de-sao-bras/"
  },
  {
    "id": "rocha-do-chambre",
    "title": "Rocha do Chambre",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/rocha-do-chambre/"
  },
  {
    "id": "rota-da-agua",
    "title": "Rota da Água",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/rota-da-agua/"
  },
  {
    "id": "serreta",
    "title": "Serreta",
    "code": "A confirmar",
    "image": "",
    "location": "Ilha Terceira, Açores",
    "distance": "A confirmar",
    "type": "A confirmar",
    "difficulty": "A confirmar",
    "duration": "A confirmar",
    "sourceUrl": "https://turismo.azores.gov.pt/pin/serreta/"
  }
];
